services:
  - type: web
    name: ghost
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: database__client
        value: sqlite3
      - key: url
        value: https://statuskuo.onrender.com
    disk:
      name: ghost-data
      mountPath: /var/lib/ghost/content
      sizeGB: 1
